@echo off

REM BootStrap
CD .\SRC\BOOT
CALL MAKEIT.BAT
CD ..\..

REM Kernel
CD .\SRC\KERNEL
make /B
CD ..\..

REM Init
CD .\SRC\INIT
CALL MAKEIT.BAT
CD ..\..

REM CS4235
CD .\SRC\CS4235
CALL MAKEIT.BAT
CD ..\..

REM Binaires
COPY /B .\SRC\BOOT\BOOT.BIN + .\SRC\KERNEL\QUICK.BIN .\BIN\DREAMOS.BIN
COPY /B .\SRC\INIT\INIT.BIN .\BIN\INIT.BIN
COPY /B .\SRC\INIT\FRENCH.BIN .\BIN\FRENCH.BIN
COPY /B .\SRC\INIT\GERMAN.BIN .\BIN\GERMAN.BIN
COPY /B .\SRC\INIT\BRITISH.BIN .\BIN\BRITISH.BIN
COPY /B .\SRC\INIT\US.BIN .\BIN\US.BIN
COPY /B .\SRC\CS4235\CS4235.BIN .\BIN\CS4235.BIN
