@echo off
cls

.\util\tinyfs "put .\bin\img\adidas.bmp /home/adidas.bmp"
.\util\tinyfs "put .\bin\img\chevry.bmp /home/chevry.bmp"
.\util\tinyfs "put .\bin\img\corto16.bmp /home/corto16.bmp"
.\util\tinyfs "put .\bin\img\duke.bmp /home/duke.bmp"
.\util\tinyfs "put .\bin\img\ibmps1.bmp /home/ibmps1.bmp"
.\util\tinyfs "put .\bin\img\lc.bmp /home/lc.bmp"
.\util\tinyfs "put .\bin\img\st.bmp /home/st.bmp"


