// FORM1.C generated by case.exe  
 
#include "quickwin.h"

#define BUTTON_ID1 1
// Variables 
HWND FormWnd; 
char bCaption1 [] = "test";

void far WinMain (void)
{
 FuncEntry
          
  if (WM_MESSAGE == WINDOW_DESTROY)
  {
   close
  }
  if (WM_MESSAGE == CONTROL_BUTTON)
  {
   if (WM_PARAM == BUTTON_ID1)
   {
   }

  }
 FuncEnd
}

void StartProgram ()
{
 FormWnd = CreateWindow (155,150,350,250,"Sample",&WinMain);
 CreateControl (65521,15,242,25,FormWnd,
                BUTTON_ID1,CONTROL_TYPE_BUTTON,_CS,(unsigned int)bCaption1,0);

}

