// FORM1.C generated by case.exe  
 
#include "quickwin.h"

#define BUTTON_ID1 1
// Variables 
HWND FormWnd; 
char bCaption1 [] = "Log on";
char eCaption1 [29] = {0,};
char eCaption2 [29] = {0,};

void far WinMain (void)
{
 FuncEntry
          
  if (WM_MESSAGE == WINDOW_DESTROY)
  {
   close
  }
  if (WM_MESSAGE == CONTROL_BUTTON)
  {
   if (WM_PARAM == BUTTON_ID1)
   {
   }

  }
 FuncEnd
}

void StartProgram ()
{
 FormWnd = CreateWindow (155,150,350,250,"Login",&WinMain);
 CreateControl (242,82,85,20,FormWnd,
                BUTTON_ID1,CONTROL_TYPE_BUTTON,_CS,(unsigned int)bCaption1,0);

 CreateControl (85,3,232,20,FormWnd,
                0,CONTROL_TYPE_EDITBOX,_CS,(unsigned int)eCaption1,0);
 CreateControl (87,36,232,20,FormWnd,
                0,CONTROL_TYPE_EDITBOX,_CS,(unsigned int)eCaption2,0);
 OutTextXY(5,10,"Login:",FormWnd);
 OutTextXY(5,41,"Password:",FormWnd);
}

