tinyfs "mkdir /qd"
tinyfs "mkdir /qd/prog"
tinyfs "put index.qdl /qd/index.qdl"
tinyfs "put dreamos.qdl /qd/dreamos.qdl"
tinyfs "put quick.qdl /qd/quick.qdl"
tinyfs "put quick.fig /qd/quick.fig"
tinyfs "put soft.qdl /qd/soft.qdl"
tinyfs "put config.qdl /qd/config.qdl"
tinyfs "put tiger.fig /qd/tiger.fig"
tinyfs "put .\prog\index.qdl /qd/prog/index.qdl"
tinyfs "put .\prog\api1.qdl /qd/prog/api1.qdl"
