tinyfs "mkdir /qd"
tinyfs "mkdir /qd/prog"
tinyfs "put index.qdl /qd/index.qdl"
tinyfs "put dreamos.qdl /qd/dreamos.qdl"
tinyfs "put quick.qdl /qd/quick.qdl"
tinyfs "put quick.fig /qd/quick.fig"
tinyfs "put soft.qdl /qd/soft.qdl"
tinyfs "put config.qdl /qd/config.qdl"
tinyfs "put tiger.fig /qd/tiger.fig"
tinyfs "put .\prog\index.qdl /qd/prog/index.qdl"
tinyfs "put .\prog\api1.qdl /qd/prog/api1.qdl"
tinyfs "put .\prog\api2.qdl /qd/prog/api2.qdl"
tinyfs "put .\prog\api3.qdl /qd/prog/api3.qdl"
tinyfs "put .\prog\api4.qdl /qd/prog/api4.qdl"
tinyfs "put .\prog\api5.qdl /qd/prog/api5.qdl"
tinyfs "put .\prog\api6.qdl /qd/prog/api6.qdl"
tinyfs "put .\prog\api7.qdl /qd/prog/api7.qdl"
tinyfs "put .\prog\tools.qdl /qd/prog/tools.qdl"
tinyfs "put .\prog\spetop.qdl /qd/prog/spetop.qdl"
tinyfs "put .\prog\eg.qdl /qd/prog/eg.qdl"
